# Generated by Django 5.0.2 on 2024-02-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productgroup_student_productgroup_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='student',
            new_name='students',
        ),
    ]
